spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            master:
                url: jdbc:mysql://localhost:3306/runda?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
                username: root
                password: 2818542061
            slave:
                enabled: false
                url:
                username:
                password:
            initialSize: 5
            minIdle: 10
            maxActive: 20
            maxWait: 60000
            connectTimeout: 30000
            socketTimeout: 60000
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            maxEvictableIdleTimeMillis: 900000
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter:
                enabled: true
            statViewServlet:
                enabled: true
                allow: 127.0.0.1  # 仅允许本地访问
                url-pattern: /druid/*
                login-username: ruoyi
                login-password: 123456
            filter:
                stat:
                    enabled: true
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true

    data:
        mongodb:
            uri: mongodb://localhost:27017/mongodb
            options:
                maxConnectionsPerHost: 100
                connectTimeoutMS: 10000  # 10秒
                socketTimeoutMS: 10000   # 10秒
                serverSelectionTimeoutMS: 10000  # 10秒

    jpa:
        hibernate:
            ddl-auto: none  # 在生产环境中建议设置为none
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect

    main:
        allow-bean-definition-overriding: true  # 启用Bean定义覆盖

mybatis-plus:
    configuration:
        map-underscore-to-camel-case: true
    global-config:
        db-config:
            id-type: auto

logging:
    level:
        com.ruoyi.system.mapper: debug
